2020-03-21 13:37:17,266 INFO: Microblog startup [in C:\Users\sgoli\Documents\flask-app\app\__init__.py:49]
2020-03-21 13:38:03,687 INFO: Microblog startup [in C:\Users\sgoli\Documents\flask-app\app\__init__.py:49]
2020-03-21 13:38:11,754 INFO: Microblog startup [in C:\Users\sgoli\Documents\flask-app\app\__init__.py:49]
2020-03-21 13:38:21,371 INFO: Microblog startup [in C:\Users\sgoli\Documents\flask-app\app\__init__.py:49]
2020-03-21 13:38:31,765 INFO: Microblog startup [in C:\Users\sgoli\Documents\flask-app\app\__init__.py:49]
2020-03-21 13:38:40,264 INFO: Microblog startup [in C:\Users\sgoli\Documents\flask-app\app\__init__.py:49]
2020-03-21 13:38:59,019 INFO: Microblog startup [in C:\Users\sgoli\Documents\flask-app\app\__init__.py:49]
2020-03-21 13:44:47,584 INFO: Microblog startup [in C:\Users\sgoli\Documents\flask-app\app\__init__.py:49]
2020-03-21 13:45:51,595 INFO: Microblog startup [in C:\Users\sgoli\Documents\flask-app\app\__init__.py:49]
2020-03-21 13:54:04,780 INFO: Microblog startup [in C:\Users\sgoli\Documents\flask-app\app\__init__.py:49]
2020-03-21 14:03:19,812 INFO: Microblog startup [in C:\Users\sgoli\Documents\flask-app\app\__init__.py:49]
2020-03-21 14:05:04,705 INFO: Microblog startup [in C:\Users\sgoli\Documents\flask-app\app\__init__.py:49]
2020-03-21 14:11:26,026 INFO: Microblog startup [in C:\Users\sgoli\Documents\flask-app\app\__init__.py:49]
2020-03-21 15:18:29,220 INFO: Microblog startup [in C:\Users\sgoli\Documents\flask-app\app\__init__.py:49]
2020-03-21 15:18:34,441 ERROR: Exception on /Inventory [GET] [in c:\users\sgoli\documents\flask-app\venv\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "c:\users\sgoli\documents\flask-app\venv\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\sgoli\documents\flask-app\venv\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\sgoli\documents\flask-app\venv\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\sgoli\documents\flask-app\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\sgoli\documents\flask-app\venv\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\sgoli\documents\flask-app\venv\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\users\sgoli\documents\flask-app\venv\lib\site-packages\flask_login\utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\sgoli\Documents\flask-app\app\routes.py", line 46, in inventory
    output = jsonify(inventory)
  File "c:\users\sgoli\documents\flask-app\venv\lib\site-packages\flask\json\__init__.py", line 370, in jsonify
    dumps(data, indent=indent, separators=separators) + "\n",
  File "c:\users\sgoli\documents\flask-app\venv\lib\site-packages\flask\json\__init__.py", line 211, in dumps
    rv = _json.dumps(obj, **kwargs)
  File "C:\Users\sgoli\AppData\Local\Programs\Python\Python37-32\lib\json\__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "C:\Users\sgoli\AppData\Local\Programs\Python\Python37-32\lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Users\sgoli\AppData\Local\Programs\Python\Python37-32\lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "c:\users\sgoli\documents\flask-app\venv\lib\site-packages\flask\json\__init__.py", line 100, in default
    return _json.JSONEncoder.default(self, o)
  File "C:\Users\sgoli\AppData\Local\Programs\Python\Python37-32\lib\json\encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type Inventory is not JSON serializable
2020-03-21 15:22:13,126 INFO: Microblog startup [in C:\Users\sgoli\Documents\flask-app\app\__init__.py:49]
2020-03-21 15:22:28,561 ERROR: Exception on /Inventory [GET] [in c:\users\sgoli\documents\flask-app\venv\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "c:\users\sgoli\documents\flask-app\venv\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\sgoli\documents\flask-app\venv\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\sgoli\documents\flask-app\venv\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\sgoli\documents\flask-app\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\sgoli\documents\flask-app\venv\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\sgoli\documents\flask-app\venv\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\users\sgoli\documents\flask-app\venv\lib\site-packages\flask_login\utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\sgoli\Documents\flask-app\app\routes.py", line 47, in inventory
    jsonOutput = jsonify(output=output)
  File "c:\users\sgoli\documents\flask-app\venv\lib\site-packages\flask\json\__init__.py", line 370, in jsonify
    dumps(data, indent=indent, separators=separators) + "\n",
  File "c:\users\sgoli\documents\flask-app\venv\lib\site-packages\flask\json\__init__.py", line 211, in dumps
    rv = _json.dumps(obj, **kwargs)
  File "C:\Users\sgoli\AppData\Local\Programs\Python\Python37-32\lib\json\__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "C:\Users\sgoli\AppData\Local\Programs\Python\Python37-32\lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Users\sgoli\AppData\Local\Programs\Python\Python37-32\lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "c:\users\sgoli\documents\flask-app\venv\lib\site-packages\flask\json\__init__.py", line 100, in default
    return _json.JSONEncoder.default(self, o)
  File "C:\Users\sgoli\AppData\Local\Programs\Python\Python37-32\lib\json\encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type InstanceState is not JSON serializable
2020-03-21 15:22:32,309 ERROR: Exception on /Inventory [GET] [in c:\users\sgoli\documents\flask-app\venv\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "c:\users\sgoli\documents\flask-app\venv\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\sgoli\documents\flask-app\venv\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\sgoli\documents\flask-app\venv\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\sgoli\documents\flask-app\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\sgoli\documents\flask-app\venv\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\sgoli\documents\flask-app\venv\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\users\sgoli\documents\flask-app\venv\lib\site-packages\flask_login\utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\sgoli\Documents\flask-app\app\routes.py", line 47, in inventory
    jsonOutput = jsonify(output=output)
  File "c:\users\sgoli\documents\flask-app\venv\lib\site-packages\flask\json\__init__.py", line 370, in jsonify
    dumps(data, indent=indent, separators=separators) + "\n",
  File "c:\users\sgoli\documents\flask-app\venv\lib\site-packages\flask\json\__init__.py", line 211, in dumps
    rv = _json.dumps(obj, **kwargs)
  File "C:\Users\sgoli\AppData\Local\Programs\Python\Python37-32\lib\json\__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "C:\Users\sgoli\AppData\Local\Programs\Python\Python37-32\lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Users\sgoli\AppData\Local\Programs\Python\Python37-32\lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "c:\users\sgoli\documents\flask-app\venv\lib\site-packages\flask\json\__init__.py", line 100, in default
    return _json.JSONEncoder.default(self, o)
  File "C:\Users\sgoli\AppData\Local\Programs\Python\Python37-32\lib\json\encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type InstanceState is not JSON serializable
2020-03-23 19:53:32,875 INFO: Microblog startup [in C:\Users\sgoli\Documents\flask-app\app\__init__.py:51]
