2020-03-23 23:27:06,660 ERROR: Exception on /Inventory [GET] [in c:\users\sgoli\documents\flask-app\venv\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "c:\users\sgoli\documents\flask-app\venv\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\sgoli\documents\flask-app\venv\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\sgoli\documents\flask-app\venv\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\sgoli\documents\flask-app\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\sgoli\documents\flask-app\venv\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\sgoli\documents\flask-app\venv\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\users\sgoli\documents\flask-app\venv\lib\site-packages\flask_login\utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\sgoli\Documents\flask-app\app\routes.py", line 53, in inventory
    return render_template('inventory.html', inventory=inventory, inventoryJSON=inventoryJSON)
  File "c:\users\sgoli\documents\flask-app\venv\lib\site-packages\flask\templating.py", line 140, in render_template
    ctx.app,
  File "c:\users\sgoli\documents\flask-app\venv\lib\site-packages\flask\templating.py", line 120, in _render
    rv = template.render(context)
  File "c:\users\sgoli\documents\flask-app\venv\lib\site-packages\jinja2\environment.py", line 1090, in render
    self.environment.handle_exception()
  File "c:\users\sgoli\documents\flask-app\venv\lib\site-packages\jinja2\environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "c:\users\sgoli\documents\flask-app\venv\lib\site-packages\jinja2\_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\sgoli\Documents\flask-app\app\templates\inventory.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "C:\Users\sgoli\Documents\flask-app\app\templates\base.html", line 1, in top-level template code
    {% extends 'bootstrap/base.html' %}
  File "c:\users\sgoli\documents\flask-app\venv\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 1, in top-level template code
    {% block doc -%}
  File "c:\users\sgoli\documents\flask-app\venv\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 3, in block "doc"
    <html{% block html_attribs %}{% endblock html_attribs %}>
  File "c:\users\sgoli\documents\flask-app\venv\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 11, in block "html"
    {%- endblock metas %}
  File "c:\users\sgoli\documents\flask-app\venv\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 13, in block "body"
    {%- block styles %}
  File "C:\Users\sgoli\Documents\flask-app\app\templates\inventory.html", line 16, in block "content"
    {{ inventoryJSON }}
  File "c:\users\sgoli\documents\flask-app\venv\lib\site-packages\markupsafe\__init__.py", line 74, in __new__
    return text_type.__new__(cls, base)
MemoryError
2020-03-23 23:28:03,281 ERROR: Exception on /Inventory [GET] [in c:\users\sgoli\documents\flask-app\venv\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "c:\users\sgoli\documents\flask-app\venv\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\sgoli\documents\flask-app\venv\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\sgoli\documents\flask-app\venv\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\sgoli\documents\flask-app\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\sgoli\documents\flask-app\venv\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\sgoli\documents\flask-app\venv\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\users\sgoli\documents\flask-app\venv\lib\site-packages\flask_login\utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\sgoli\Documents\flask-app\app\routes.py", line 53, in inventory
  File "c:\users\sgoli\documents\flask-app\venv\lib\site-packages\flask\templating.py", line 140, in render_template
    ctx.app,
  File "c:\users\sgoli\documents\flask-app\venv\lib\site-packages\flask\templating.py", line 120, in _render
    rv = template.render(context)
  File "c:\users\sgoli\documents\flask-app\venv\lib\site-packages\jinja2\environment.py", line 1090, in render
    self.environment.handle_exception()
  File "c:\users\sgoli\documents\flask-app\venv\lib\site-packages\jinja2\environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "c:\users\sgoli\documents\flask-app\venv\lib\site-packages\jinja2\_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\sgoli\Documents\flask-app\app\templates\inventory.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "C:\Users\sgoli\Documents\flask-app\app\templates\base.html", line 1, in top-level template code
    {% extends 'bootstrap/base.html' %}
  File "c:\users\sgoli\documents\flask-app\venv\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 1, in top-level template code
    {% block doc -%}
  File "c:\users\sgoli\documents\flask-app\venv\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 3, in block "doc"
    <html{% block html_attribs %}{% endblock html_attribs %}>
  File "c:\users\sgoli\documents\flask-app\venv\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 11, in block "html"
    {%- endblock metas %}
  File "c:\users\sgoli\documents\flask-app\venv\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 13, in block "body"
    {%- block styles %}
  File "C:\Users\sgoli\Documents\flask-app\app\templates\inventory.html", line 16, in block "content"
    </p>
  File "c:\users\sgoli\documents\flask-app\venv\lib\site-packages\markupsafe\__init__.py", line 74, in __new__
    return text_type.__new__(cls, base)
MemoryError
2020-03-23 23:28:29,457 INFO: Microblog startup [in C:\Users\sgoli\Documents\flask-app\app\__init__.py:51]
2020-03-23 23:29:11,153 INFO: Microblog startup [in C:\Users\sgoli\Documents\flask-app\app\__init__.py:51]
2020-03-23 23:33:53,919 INFO: Microblog startup [in C:\Users\sgoli\Documents\flask-app\app\__init__.py:51]
2020-03-23 23:41:27,629 INFO: Microblog startup [in C:\Users\sgoli\Documents\flask-app\app\__init__.py:51]
2020-03-23 23:45:13,387 INFO: Microblog startup [in C:\Users\sgoli\Documents\flask-app\app\__init__.py:51]
2020-03-23 23:45:28,556 INFO: Microblog startup [in C:\Users\sgoli\Documents\flask-app\app\__init__.py:51]
2020-03-23 23:45:44,273 INFO: Microblog startup [in C:\Users\sgoli\Documents\flask-app\app\__init__.py:51]
2020-03-23 23:46:05,975 INFO: Microblog startup [in C:\Users\sgoli\Documents\flask-app\app\__init__.py:51]
2020-03-23 23:51:02,605 INFO: Microblog startup [in C:\Users\sgoli\Documents\flask-app\app\__init__.py:51]
2020-03-23 23:53:05,987 INFO: Microblog startup [in C:\Users\sgoli\Documents\flask-app\app\__init__.py:51]
2020-03-23 23:54:30,651 INFO: Microblog startup [in C:\Users\sgoli\Documents\flask-app\app\__init__.py:51]
2020-03-23 23:59:31,427 INFO: Microblog startup [in C:\Users\sgoli\Documents\flask-app\app\__init__.py:51]
2020-03-24 00:00:11,702 INFO: Microblog startup [in C:\Users\sgoli\Documents\flask-app\app\__init__.py:51]
2020-03-24 00:01:29,906 INFO: Microblog startup [in C:\Users\sgoli\Documents\flask-app\app\__init__.py:51]
2020-03-24 00:03:21,743 INFO: Microblog startup [in C:\Users\sgoli\Documents\flask-app\app\__init__.py:51]
2020-03-24 00:08:00,075 INFO: Microblog startup [in C:\Users\sgoli\Documents\flask-app\app\__init__.py:51]
2020-03-24 00:09:00,987 INFO: Microblog startup [in C:\Users\sgoli\Documents\flask-app\app\__init__.py:51]
2020-03-24 00:09:43,957 INFO: Microblog startup [in C:\Users\sgoli\Documents\flask-app\app\__init__.py:51]
2020-03-24 00:10:10,768 INFO: Microblog startup [in C:\Users\sgoli\Documents\flask-app\app\__init__.py:51]
2020-03-24 00:10:49,581 INFO: Microblog startup [in C:\Users\sgoli\Documents\flask-app\app\__init__.py:51]
2020-03-24 00:12:59,957 INFO: Microblog startup [in C:\Users\sgoli\Documents\flask-app\app\__init__.py:51]
2020-03-24 00:13:46,932 INFO: Microblog startup [in C:\Users\sgoli\Documents\flask-app\app\__init__.py:51]
2020-03-24 00:14:42,415 INFO: Microblog startup [in C:\Users\sgoli\Documents\flask-app\app\__init__.py:51]
2020-03-24 00:15:58,778 INFO: Microblog startup [in C:\Users\sgoli\Documents\flask-app\app\__init__.py:51]
2020-03-24 00:16:52,540 INFO: Microblog startup [in C:\Users\sgoli\Documents\flask-app\app\__init__.py:51]
2020-03-24 10:08:40,027 INFO: Microblog startup [in C:\Users\sgoli\Documents\flask-app\app\__init__.py:51]
2020-03-24 10:15:00,948 INFO: Microblog startup [in C:\Users\sgoli\Documents\flask-app\app\__init__.py:51]
2020-03-24 10:18:58,767 INFO: Microblog startup [in C:\Users\sgoli\Documents\flask-app\app\__init__.py:51]
2020-03-24 10:19:44,398 INFO: Microblog startup [in C:\Users\sgoli\Documents\flask-app\app\__init__.py:51]
2020-03-24 10:26:33,238 INFO: Microblog startup [in C:\Users\sgoli\Documents\flask-app\app\__init__.py:51]
2020-03-24 10:27:04,758 INFO: Microblog startup [in C:\Users\sgoli\Documents\flask-app\app\__init__.py:51]
