2020-03-19 09:48:03,582 ERROR: Exception on /user/susan [GET] [in c:\users\sgoli\documents\flask-app\venv\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "c:\users\sgoli\documents\flask-app\venv\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\sgoli\documents\flask-app\venv\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\sgoli\documents\flask-app\venv\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\sgoli\documents\flask-app\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\sgoli\documents\flask-app\venv\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\sgoli\documents\flask-app\venv\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\users\sgoli\documents\flask-app\venv\lib\site-packages\flask_login\utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\sgoli\Documents\flask-app\app\routes.py", line 76, in user
    return render_template('user.html', user=user, posts=posts)
  File "c:\users\sgoli\documents\flask-app\venv\lib\site-packages\flask\templating.py", line 140, in render_template
    ctx.app,
  File "c:\users\sgoli\documents\flask-app\venv\lib\site-packages\flask\templating.py", line 120, in _render
    rv = template.render(context)
  File "c:\users\sgoli\documents\flask-app\venv\lib\site-packages\jinja2\environment.py", line 1090, in render
    self.environment.handle_exception()
  File "c:\users\sgoli\documents\flask-app\venv\lib\site-packages\jinja2\environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "c:\users\sgoli\documents\flask-app\venv\lib\site-packages\jinja2\_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\sgoli\Documents\flask-app\app\templates\user.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "C:\Users\sgoli\Documents\flask-app\app\templates\base.html", line 29, in top-level template code
    {% block content %}{% endblock %}
  File "C:\Users\sgoli\Documents\flask-app\app\templates\user.html", line 14, in block "content"
    {% elif not current_user.is_following(user) %}
  File "C:\Users\sgoli\Documents\flask-app\app\models.py", line 49, in is_following
    return self.followed.filter(followers.c.followed_id == user.id).cout() > 0
AttributeError: 'BaseQuery' object has no attribute 'cout'
2020-03-19 09:48:27,702 INFO: Microblog startup [in C:\Users\sgoli\Documents\flask-app\app\__init__.py:44]
2020-03-19 10:03:46,314 INFO: Microblog startup [in C:\Users\sgoli\Documents\flask-app\app\__init__.py:44]
2020-03-19 10:06:26,992 ERROR: Exception on /index [GET] [in c:\users\sgoli\documents\flask-app\venv\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "c:\users\sgoli\documents\flask-app\venv\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\sgoli\documents\flask-app\venv\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\sgoli\documents\flask-app\venv\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\sgoli\documents\flask-app\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\sgoli\documents\flask-app\venv\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\sgoli\documents\flask-app\venv\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\users\sgoli\documents\flask-app\venv\lib\site-packages\flask_login\utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\sgoli\Documents\flask-app\app\routes.py", line 27, in index
    return render_template('index.html', title='Home Page', form=form, posts=posts)
  File "c:\users\sgoli\documents\flask-app\venv\lib\site-packages\flask\templating.py", line 140, in render_template
    ctx.app,
  File "c:\users\sgoli\documents\flask-app\venv\lib\site-packages\flask\templating.py", line 120, in _render
    rv = template.render(context)
  File "c:\users\sgoli\documents\flask-app\venv\lib\site-packages\jinja2\environment.py", line 1090, in render
    self.environment.handle_exception()
  File "c:\users\sgoli\documents\flask-app\venv\lib\site-packages\jinja2\environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "c:\users\sgoli\documents\flask-app\venv\lib\site-packages\jinja2\_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\sgoli\Documents\flask-app\app\templates\index.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "C:\Users\sgoli\Documents\flask-app\app\templates\base.html", line 30, in top-level template code
    {% block content %}{% endblock %}
  File "C:\Users\sgoli\Documents\flask-app\app\templates\index.html", line 18, in block "content"
    {% include '__post.html' %}
  File "c:\users\sgoli\documents\flask-app\venv\lib\site-packages\flask\templating.py", line 60, in get_source
    return self._get_source_fast(environment, template)
  File "c:\users\sgoli\documents\flask-app\venv\lib\site-packages\flask\templating.py", line 89, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: __post.html
2020-03-19 10:07:12,577 INFO: Microblog startup [in C:\Users\sgoli\Documents\flask-app\app\__init__.py:44]
2020-03-19 10:15:58,499 INFO: Microblog startup [in C:\Users\sgoli\Documents\flask-app\app\__init__.py:44]
2020-03-19 10:26:43,853 INFO: Microblog startup [in C:\Users\sgoli\Documents\flask-app\app\__init__.py:44]
2020-03-19 10:31:00,408 INFO: Microblog startup [in C:\Users\sgoli\Documents\flask-app\app\__init__.py:46]
2020-03-19 11:23:52,965 INFO: Microblog startup [in C:\Users\sgoli\Documents\flask-app\app\__init__.py:46]
2020-03-19 11:29:36,646 INFO: Microblog startup [in C:\Users\sgoli\Documents\flask-app\app\__init__.py:46]
2020-03-19 11:30:41,693 INFO: Microblog startup [in C:\Users\sgoli\Documents\flask-app\app\__init__.py:46]
2020-03-19 11:30:52,300 ERROR: Exception on /reset_password_request [GET] [in c:\users\sgoli\documents\flask-app\venv\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "c:\users\sgoli\documents\flask-app\venv\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\sgoli\documents\flask-app\venv\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\sgoli\documents\flask-app\venv\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\sgoli\documents\flask-app\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\sgoli\documents\flask-app\venv\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\sgoli\documents\flask-app\venv\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\sgoli\Documents\flask-app\app\routes.py", line 136, in reset_password_request
    form = ResetPasswordRequestForm()
NameError: name 'ResetPasswordRequestForm' is not defined
2020-03-20 13:57:46,684 INFO: Microblog startup [in C:\Users\sgoli\Documents\flask-app\app\__init__.py:46]
2020-03-20 14:17:30,680 INFO: Microblog startup [in C:\Users\sgoli\Documents\flask-app\app\__init__.py:48]
2020-03-20 14:21:17,654 INFO: Microblog startup [in C:\Users\sgoli\Documents\flask-app\app\__init__.py:48]
2020-03-20 14:23:50,186 INFO: Microblog startup [in C:\Users\sgoli\Documents\flask-app\app\__init__.py:48]
2020-03-20 14:28:38,413 INFO: Microblog startup [in C:\Users\sgoli\Documents\flask-app\app\__init__.py:48]
2020-03-20 19:57:27,844 INFO: Microblog startup [in C:\Users\sgoli\Documents\flask-app\app\__init__.py:50]
2020-03-20 20:04:53,916 INFO: Microblog startup [in C:\Users\sgoli\Documents\flask-app\app\__init__.py:52]
2020-03-20 20:05:36,729 INFO: Microblog startup [in C:\Users\sgoli\Documents\flask-app\app\__init__.py:50]
2020-03-20 20:29:52,013 INFO: Microblog startup [in C:\Users\sgoli\Documents\flask-app\app\__init__.py:49]
2020-03-21 13:17:54,071 INFO: Microblog startup [in C:\Users\sgoli\Documents\flask-app\app\__init__.py:49]
2020-03-21 13:18:06,264 INFO: Microblog startup [in C:\Users\sgoli\Documents\flask-app\app\__init__.py:49]
2020-03-21 13:33:23,758 INFO: Microblog startup [in C:\Users\sgoli\Documents\flask-app\app\__init__.py:49]
2020-03-21 13:33:37,699 INFO: Microblog startup [in C:\Users\sgoli\Documents\flask-app\app\__init__.py:49]
2020-03-21 13:34:59,840 INFO: Microblog startup [in C:\Users\sgoli\Documents\flask-app\app\__init__.py:49]
2020-03-21 13:35:06,475 INFO: Microblog startup [in C:\Users\sgoli\Documents\flask-app\app\__init__.py:49]
2020-03-21 13:35:23,093 INFO: Microblog startup [in C:\Users\sgoli\Documents\flask-app\app\__init__.py:49]
2020-03-21 13:35:35,052 INFO: Microblog startup [in C:\Users\sgoli\Documents\flask-app\app\__init__.py:49]
2020-03-21 13:35:55,880 INFO: Microblog startup [in C:\Users\sgoli\Documents\flask-app\app\__init__.py:49]
2020-03-21 13:36:09,511 INFO: Microblog startup [in C:\Users\sgoli\Documents\flask-app\app\__init__.py:49]
2020-03-21 13:36:22,100 INFO: Microblog startup [in C:\Users\sgoli\Documents\flask-app\app\__init__.py:49]
